### ISSUE TITLE
Wiping a playground and pressing "Proper save" crashes Xcode

### ISSUE THREAD

**Issue by NSElvis** [zenangst/MarvinXcode#9] opened 2014-12-01 09:51 UTC

**Comment by zenangst** [comment] 2015-02-06 07:27
I think that was just Xcode being an asshole, unable to reproduce this.

**Comment by zenangst** [comment] 2015-02-06 08:20
My bad!

**Comment by zenangst** [comment] 2015-02-06 08:49
Fixed in https://github.com/zenangst/MarvinXcode/pull/11

**Closed by zenangst** 2015-02-06 08:49 UTC

**Comment by NSElvis** [comment] 2015-02-06 08:51
:star:  :hamburger: :star:
